gazebo_ros_control:
  pid_gains:
    panda_joint1: {p: 80000, i: 0, d: 700}
    panda_joint2: {p: 80000, i: 0, d: 700}
    panda_joint3: {p: 80000, i: 0, d: 700}
    panda_joint4: {p: 80000, i: 0, d: 700}
    panda_joint5: {p: 80000, i: 0, d: 700}
    panda_joint6: {p: 80000, i: 0, d: 700}
    panda_joint7: {p: 80000, i: 0.5, d: 700}
    panda_finger_joint1: {p: 100, i: 0, d: 50}
    panda_finger_joint2: {p: 100, i: 0, d: 50}